import AVFoundation
import Foundation

// MARK: - Audio injection harness
//
// The problem this solves: nobody can hold a hotkey and speak on demand, so
// every stage after the microphone was unverifiable. This feeds pre-recorded
// audio straight into the same `[Float]` 16 kHz mono seam the mic produces, and
// then runs the real transcriber, the real parser, the real resolver and the
// real deep-link builder over it.
//
// Nothing here is stubbed. If the transcriber cannot transcribe, the harness
// reports a failure — it never substitutes a canned string.
//
// Usage (run the BUNDLED binary so TCC permissions apply):
//   dist/Voicy.app/Contents/MacOS/Voicy --test-audio Tests/audio/msg-pulkit.wav
//   dist/Voicy.app/Contents/MacOS/Voicy --test-audio-suite Tests/audio/manifest.tsv
//   dist/Voicy.app/Contents/MacOS/Voicy --unit-tests
//
// Flags:
//   --expect-recipient <name>   assert the resolved contact's display name
//   --expect-body <text>        assert the message body (loose match by default)
//   --expect-transcript <text>  assert the transcript (loose match by default)
//   --strict                    make the assertions byte-exact
//   --real-contacts             use the address book instead of the fixtures
//   --repeat <n>                run the clip n times (latency measurement)
//   --quiet                     one summary line per clip, no stage table

/// Sync entry for main.swift, mirroring `runSelfTestIfRequested()`. Returns
/// immediately unless a test flag is present; otherwise runs and exits.
@MainActor
func runTestHarnessIfRequested() {
    let args = CommandLine.arguments
    let modes = ["--test-audio", "--test-audio-suite", "--unit-tests", "--test-latency",
                 "--test-wer", "--test-onset", "--test-stream"]
    guard args.contains(where: { modes.contains($0) }) else { return }

    let done = CompletionFlag()
    var exitCode: Int32 = 0

    Task { @MainActor in
        exitCode = await TestHarness(args: args).run()
        done.value = true
    }

    // Pump the main run loop rather than blocking on a semaphore: parts of the
    // pipeline (ContactIndex) are main-actor isolated, so a blocked main thread
    // would deadlock instead of finishing.
    while !done.value {
        RunLoop.main.run(mode: .default, before: Date().addingTimeInterval(0.01))
    }
    exit(exitCode)
}

@MainActor
private final class CompletionFlag {
    var value = false
}

/// Collects timestamped partial results from a streaming session. The callback
/// fires from the recognizer's own task, so this is locked rather than
/// main-actor isolated.
private final class PartialRecorder: @unchecked Sendable {
    private var entries: [(String, Double)] = []
    private let lock = NSLock()

    func record(text: String, at ms: Double) {
        lock.lock()
        entries.append((text, ms))
        lock.unlock()
    }

    func snapshot() -> [(String, Double)] {
        lock.lock()
        defer { lock.unlock() }
        return entries
    }
}

// MARK: - Harness

@MainActor
struct TestHarness {
    let args: [String]

    // MARK: Flag access

    private func value(for flag: String) -> String? {
        guard let i = args.firstIndex(of: flag), i + 1 < args.count else { return nil }
        let next = args[i + 1]
        return next.hasPrefix("--") ? nil : next
    }

    private func has(_ flag: String) -> Bool { args.contains(flag) }

    private var strict: Bool { has("--strict") }

    /// Print character counts instead of text. The harness normally shows the
    /// transcript, which is the whole point of it, and that is safe because it
    /// runs on synthetic clips generated by `say`. Pointed at REAL audio (a
    /// WhatsApp voice note, a real recording) it would put someone's private
    /// message on stdout, and stdout gets redirected to a file. `--redact` is
    /// the mode for that case: it still proves the pipeline ran end to end,
    /// without disclosing what was said.
    private var redact: Bool { has("--redact") }

    /// Text as the report should show it.
    private func display(_ text: String) -> String {
        redact ? "[redacted, \(text.count) chars]" : text
    }
    private var quiet: Bool { has("--quiet") }
    private var repeatCount: Int { max(1, Int(value(for: "--repeat") ?? "1") ?? 1) }

    // MARK: Entry

    func run() async -> Int32 {
        var failures = 0

        if has("--unit-tests") {
            failures += await runUnitTests()
        }

        if let path = value(for: "--test-audio") {
            let contacts = await contactSet()
            let engine = await warmEngine()
            var results: [InjectionOutcome] = []
            for iteration in 0..<repeatCount {
                let outcome = await inject(path: path, contacts: contacts, engine: engine,
                                           label: repeatCount > 1 ? "run \(iteration + 1)/\(repeatCount)" : nil)
                results.append(outcome)
            }
            failures += report(results, contacts: contacts)
        }

        if let manifest = value(for: "--test-audio-suite") {
            failures += await runSuite(manifestPath: manifest)
        }

        if let manifest = value(for: "--test-wer") {
            failures += await runWER(manifestPath: manifest)
        }

        if let path = value(for: "--test-stream") {
            failures += await runStreamProbe(path: path)
        }

        if has("--test-onset") {
            await runOnsetProbe()
        }

        if has("--test-latency") {
            await runLatencyProbe()
        }

        print("")
        if failures == 0 {
            print("RESULT: all checks passed")
            return 0
        }
        print("RESULT: \(failures) check(s) FAILED")
        return 1
    }

    // MARK: - Setup

    private func contactSet() async -> [Contact] {
        guard has("--real-contacts") else { return FixtureContacts.all }
        let index = ContactIndex()
        do {
            try await index.load()
            print("contacts: \(index.contacts.count) loaded from the address book")
            return index.contacts
        } catch {
            print("contacts: address book unavailable (\(error)); falling back to fixtures")
            return FixtureContacts.all
        }
    }

    /// Builds the transcriber and pays its first-call cost up front so the
    /// measured numbers reflect a warm engine, the way the shipped app behaves
    /// once `TranscriberWarmup` has run.
    private func warmEngine() async -> Transcriber {
        let engine = TranscriberFactory.make()
        let t0 = Date()
        // 300 ms of silence: enough to force model load, short enough to be free.
        let silence = [Float](repeating: 0, count: 4_800)
        _ = try? await engine.transcribe(pcm: silence, hints: [])
        let ms = Date().timeIntervalSince(t0) * 1000
        print("engine: \(String(describing: type(of: engine))) warmed in \(fmt(ms)) ms")
        return engine
    }

    // MARK: - One clip through the pipeline

    struct InjectionOutcome {
        var path: String
        var label: String?
        var samples: Int
        var duration: Double
        var peak: Float
        var rms: Float
        var decodeMs: Double = 0
        var transcribeMs: Double = 0
        var parseMs: Double = 0
        var resolveMs: Double = 0
        var linkMs: Double = 0
        var transcript: String = ""
        var alternatives: [String] = []
        var recipientText: String?
        var body: String?
        var resolution: String = "—"
        var resolvedName: String?
        var resolvedPhone: String?
        var deepLink: String?
        var errors: [String] = []

        var totalMs: Double { decodeMs + transcribeMs + parseMs + resolveMs + linkMs }
    }

    private func inject(path: String, contacts: [Contact], engine: Transcriber,
                        label: String?) async -> InjectionOutcome {
        let url = URL(fileURLWithPath: path)

        let decodeStart = Date()
        let pcm: [Float]
        do {
            pcm = try AudioFileLoader.loadPCM(url: url)
        } catch {
            var out = InjectionOutcome(path: path, label: label, samples: 0,
                                       duration: 0, peak: 0, rms: 0)
            out.errors.append("decode: \(error)")
            return out
        }
        var out = InjectionOutcome(path: path, label: label,
                                   samples: pcm.count,
                                   duration: AudioFileLoader.duration(pcm),
                                   peak: AudioFileLoader.peak(pcm),
                                   rms: AudioFileLoader.rms(pcm))
        out.decodeMs = Date().timeIntervalSince(decodeStart) * 1000

        if out.samples == 0 {
            out.errors.append("decode: file produced zero samples")
            return out
        }
        if out.peak < 0.001 {
            out.errors.append("audio: clip is silent (peak \(out.peak)); transcription cannot succeed")
        }

        // Stage: transcription, biased by contact names exactly as the app does.
        // `--no-hints` drops the bias so the two runs can be compared directly:
        // if the transcripts are identical, the biasing is a no-op and the
        // accuracy feature does not actually exist.
        let hints = has("--no-hints") ? [] : contacts.flatMap { c in
            [c.givenName, c.familyName, c.nickname, c.organizationName, c.displayName]
                .filter { !$0.isEmpty }
        }
        let transcribeStart = Date()
        do {
            let result = try await engine.transcribeDetailed(pcm: pcm, hints: hints)
            out.transcript = result.best
            out.alternatives = result.hypotheses.dropFirst().map { $0 }
        } catch {
            out.transcribeMs = Date().timeIntervalSince(transcribeStart) * 1000
            out.errors.append("transcribe: \(error)")
            return out
        }
        out.transcribeMs = Date().timeIntervalSince(transcribeStart) * 1000

        if out.transcript.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            out.errors.append("transcribe: empty transcript from \(out.duration.rounded()) s of audio")
            return out
        }

        // Stage: intent parse.
        let parseStart = Date()
        let parsed = IntentParser().parse(out.transcript)
        out.parseMs = Date().timeIntervalSince(parseStart) * 1000

        guard case .parsed(let intent) = parsed else {
            if case .notParsed(let reason) = parsed {
                out.errors.append("parse: notParsed(\(reason))")
            }
            return out
        }
        out.recipientText = intent.recipientText
        out.body = intent.body

        // Hard rule: the body is sliced from the transcript, never regenerated.
        if !out.transcript.contains(intent.body) {
            out.errors.append("FIDELITY VIOLATION: body is not a verbatim slice of the transcript")
        }

        // Stage: contact resolution.
        let resolveStart = Date()
        let resolution = ContactResolver().resolve(spoken: intent.recipientText,
                                                   contacts: contacts,
                                                   aliases: [:])
        out.resolveMs = Date().timeIntervalSince(resolveStart) * 1000

        switch resolution {
        case .resolved(let contact):
            out.resolution = "resolved"
            out.resolvedName = contact.displayName
            out.resolvedPhone = contact.preferredE164
            if contact.preferredE164 == nil {
                out.resolution = "resolved (no phone number)"
            }
        case .ambiguous(let candidates):
            out.resolution = "ambiguous: " + candidates.map(\.displayName).joined(separator: ", ")
            // Record the top candidate so a test can assert "the right person was
            // OFFERED" even when the name was too mangled to resolve outright.
            // No phone is recorded, so no deep link is built: an ambiguous match
            // must never become a send without the user choosing.
            out.resolvedName = candidates.first?.displayName
        case .notFound:
            out.resolution = "notFound"
        }

        // Stage: deep link. Dry run — built and inspected, never opened.
        if let phone = out.resolvedPhone {
            let linkStart = Date()
            do {
                let url = try WhatsAppDeepLink.sendURL(phone: phone, text: intent.body)
                out.deepLink = url.absoluteString
            } catch {
                out.errors.append("deeplink: \(error)")
            }
            out.linkMs = Date().timeIntervalSince(linkStart) * 1000
        }

        return out
    }

    // MARK: - Reporting

    private func report(_ results: [InjectionOutcome], contacts: [Contact]) -> Int {
        var failures = 0
        for out in results {
            failures += printOutcome(out)
        }

        if results.count > 1 {
            let ok = results.filter { $0.errors.isEmpty }
            let times = ok.map(\.transcribeMs).sorted()
            if !times.isEmpty {
                let median = times[times.count / 2]
                print("")
                print("transcription over \(times.count) run(s): min \(fmt(times.first!)) ms  "
                      + "median \(fmt(median)) ms  max \(fmt(times.last!)) ms  (budget 800 ms)")
                if median > 800 { print("  OVER BUDGET by \(fmt(median - 800)) ms") }
            }
        }

        failures += checkExpectations(results)
        _ = contacts
        return failures
    }

    private func printOutcome(_ out: InjectionOutcome) -> Int {
        if quiet {
            let verdict = out.errors.isEmpty ? "ok  " : "FAIL"
            print("\(verdict) \(URL(fileURLWithPath: out.path).lastPathComponent)  "
                  + "\(fmt(out.transcribeMs))ms  \"\(display(out.transcript))\"")
            for e in out.errors { print("       \(e)") }
            return out.errors.isEmpty ? 0 : 1
        }

        print("")
        print("=== audio injection: \(URL(fileURLWithPath: out.path).lastPathComponent)"
              + (out.label.map { " (\($0))" } ?? "") + " ===")
        print("  audio       \(String(format: "%.2f", out.duration)) s, \(out.samples) samples @16kHz, "
              + "peak \(String(format: "%.3f", out.peak)), rms \(String(format: "%.3f", out.rms))")
        print("  decode      \(fmt(out.decodeMs)) ms")
        print("  transcribe  \(fmt(out.transcribeMs)) ms   \"\(display(out.transcript))\"")
        if out.alternatives.isEmpty {
            print("  alternates  none offered by the engine")
        } else {
            for (i, alt) in out.alternatives.enumerated() {
                print("  alternate \(i + 1)              \"\(display(alt))\"")
            }
        }
        if let recipient = out.recipientText, let body = out.body {
            print("  parse       \(fmt(out.parseMs)) ms   recipient=\"\(recipient)\" body=\"\(display(body))\"")
            print("  resolve     \(fmt(out.resolveMs)) ms   \(out.resolution)"
                  + (out.resolvedPhone.map { " +\($0)" } ?? ""))
        }
        if let link = out.deepLink {
            print("  deeplink    \(fmt(out.linkMs)) ms   \(redact ? String(link.prefix(38)) + "…[redacted]" : link)")
            print("  send        DRY RUN — link built, not opened")
        }
        print("  total       \(fmt(out.totalMs)) ms")

        if out.errors.isEmpty {
            print("  verdict     PASS")
            return 0
        }
        for e in out.errors { print("  ERROR       \(e)") }
        print("  verdict     FAIL")
        return 1
    }

    private func checkExpectations(_ results: [InjectionOutcome]) -> Int {
        guard let first = results.first else { return 0 }
        var failures = 0

        func check(_ label: String, got: String?, want: String) {
            guard let got else {
                print("EXPECT FAIL \(label): got nothing, want \"\(want)\"")
                failures += 1
                return
            }
            let ok = strict ? got == want : loosely(got, equals: want)
            if ok {
                print("EXPECT PASS \(label): \"\(got)\"")
            } else {
                print("EXPECT FAIL \(label): got \"\(got)\", want \"\(want)\"")
                failures += 1
            }
        }

        if let want = value(for: "--expect-transcript") {
            check("transcript", got: first.transcript, want: want)
        }
        if let want = value(for: "--expect-recipient") {
            check("recipient", got: first.resolvedName ?? first.recipientText, want: want)
        }
        if let want = value(for: "--expect-body") {
            check("body", got: first.body, want: want)
        }
        return failures
    }

    /// Loose comparison: case-insensitive, punctuation-insensitive, whitespace
    /// collapsed. Speech recognizers capitalize and punctuate at their own
    /// discretion, so an exact match would fail for reasons that are not bugs.
    /// `--strict` opts into byte-exact comparison.
    private func loosely(_ a: String, equals b: String) -> Bool {
        canon(a) == canon(b)
    }

    /// Number words and digits are treated as equal: a recognizer writing "10"
    /// for spoken "ten" is a formatting choice, not a transcription error, and
    /// asserting on it would make the suite fail for a non-bug.
    private static let numberWords: [String: String] = [
        "zero": "0", "one": "1", "two": "2", "three": "3", "four": "4",
        "five": "5", "six": "6", "seven": "7", "eight": "8", "nine": "9",
        "ten": "10", "eleven": "11", "twelve": "12", "twenty": "20",
        "thirty": "30", "forty": "40", "fifty": "50", "hundred": "100",
    ]

    private func canon(_ s: String) -> String {
        let stripped = s.unicodeScalars.filter { scalar in
            CharacterSet.alphanumerics.contains(scalar) || scalar == " "
        }
        return String(String.UnicodeScalarView(stripped))
            .lowercased()
            .split(separator: " ", omittingEmptySubsequences: true)
            .map { Self.numberWords[String($0)] ?? String($0) }
            .joined(separator: " ")
    }

    // MARK: - Suite mode

    /// Runs every clip in a tab-separated manifest:
    ///   name <TAB> voice <TAB> spoken text <TAB> expect-recipient <TAB> expect-body
    /// Lines starting with `#` and blank lines are ignored. Audio is expected at
    /// `<manifest dir>/<name>.wav` (generate it with Tools/gen-test-audio.sh).
    private func runSuite(manifestPath: String) async -> Int {
        let manifestURL = URL(fileURLWithPath: manifestPath)
        guard let text = try? String(contentsOf: manifestURL, encoding: .utf8) else {
            print("suite: could not read manifest at \(manifestPath)")
            return 1
        }
        let dir = manifestURL.deletingLastPathComponent()
        let cases = AudioManifest.parse(text)
        guard !cases.isEmpty else {
            print("suite: manifest has no cases")
            return 1
        }

        let contacts = await contactSet()
        let engine = await warmEngine()

        print("")
        print("=== audio suite: \(cases.count) clip(s) ===")

        var failures = 0
        var transcribeTimes: [Double] = []

        for testCase in cases {
            let audioURL = dir.appendingPathComponent("\(testCase.name).wav")
            guard FileManager.default.fileExists(atPath: audioURL.path) else {
                print("FAIL \(testCase.name): audio missing at \(audioURL.path) — run Tools/gen-test-audio.sh")
                failures += 1
                continue
            }
            let out = await inject(path: audioURL.path, contacts: contacts, engine: engine, label: nil)
            transcribeTimes.append(out.transcribeMs)

            var caseFailures = out.errors

            // A case can expect REJECTION. "notParsed" means the utterance must
            // not become a message at all, so a parse failure is the pass
            // condition and its absence is the failure.
            if testCase.expectResolution.lowercased() == "notparsed" {
                let rejected = out.errors.contains { $0.hasPrefix("parse: notParsed") }
                caseFailures = out.errors.filter { !$0.hasPrefix("parse: notParsed") }
                if !rejected {
                    caseFailures.append("expected the utterance to be REJECTED, "
                                        + "but it parsed as recipient=\"\(out.recipientText ?? "")\"")
                }
                if caseFailures.isEmpty {
                    print("PASS \(pad(testCase.name, 22)) \(pad(fmt(out.transcribeMs) + "ms", 9)) "
                          + "rejected (correct)  \"\(display(out.transcript))\"")
                } else {
                    failures += 1
                    print("FAIL \(pad(testCase.name, 22)) \(pad(fmt(out.transcribeMs) + "ms", 9)) \"\(display(out.transcript))\"")
                    for f in caseFailures { print("       \(f)") }
                }
                continue
            }

            if !testCase.expectRecipient.isEmpty {
                let got = out.resolvedName ?? out.recipientText ?? ""
                if !loosely(got, equals: testCase.expectRecipient) {
                    caseFailures.append("recipient: got \"\(got)\", want \"\(testCase.expectRecipient)\"")
                }
            }
            if !testCase.expectBody.isEmpty {
                let got = out.body ?? ""
                if !loosely(got, equals: testCase.expectBody) {
                    caseFailures.append("body: got \"\(got)\", want \"\(testCase.expectBody)\"")
                }
            }
            if !testCase.expectResolution.isEmpty,
               !out.resolution.lowercased().hasPrefix(testCase.expectResolution.lowercased()) {
                caseFailures.append("resolution: got \"\(out.resolution)\", want \"\(testCase.expectResolution)\"")
            }

            if caseFailures.isEmpty {
                print("PASS \(pad(testCase.name, 22)) \(pad(fmt(out.transcribeMs) + "ms", 9)) \"\(display(out.transcript))\"")
            } else {
                failures += 1
                print("FAIL \(pad(testCase.name, 22)) \(pad(fmt(out.transcribeMs) + "ms", 9)) \"\(display(out.transcript))\"")
                for f in caseFailures { print("       \(f)") }
            }
        }

        let sorted = transcribeTimes.sorted()
        if !sorted.isEmpty {
            print("")
            print("suite transcription: min \(fmt(sorted.first!)) ms  "
                  + "median \(fmt(sorted[sorted.count / 2])) ms  max \(fmt(sorted.last!)) ms  (budget 800 ms)")
        }
        print("suite: \(cases.count - failures)/\(cases.count) passed")
        return failures
    }

    // MARK: - Streaming probe

    /// Proves the streaming path actually streams, and that streaming does not
    /// change the answer.
    ///
    /// The clip is fed in 100 ms chunks at real-time pace, exactly as the
    /// microphone tap would deliver it, and every partial is timestamped. Two
    /// things are checked, both of which are how streaming normally goes wrong:
    ///
    ///   1. Partials must arrive BEFORE the audio ends. A "streaming" API that
    ///      only emits once at the end has no user-visible benefit at all.
    ///   2. The final text must match the one-shot transcript. If streaming
    ///      changes the result, the app would ship two different recognizers
    ///      depending on which path ran.
    ///
    ///   Voicy --test-stream Tests/audio/long-body.wav
    private func runStreamProbe(path: String) async -> Int {
        guard #available(macOS 26.0, *) else {
            print("stream: needs macOS 26")
            return 1
        }
        print("")
        print("=== streaming probe: \(URL(fileURLWithPath: path).lastPathComponent) ===")

        guard let pcm = try? AudioFileLoader.loadPCM(url: URL(fileURLWithPath: path)), !pcm.isEmpty else {
            print("stream: could not load audio at \(path)")
            return 1
        }
        let duration = AudioFileLoader.duration(pcm)
        let contacts = await contactSet()
        let hints = contacts.flatMap { c in
            [c.givenName, c.familyName, c.nickname, c.organizationName, c.displayName].filter { !$0.isEmpty }
        }

        let recorder = PartialRecorder()
        let start = Date()
        let session = LiveTranscriptionSession(locale: Locale(identifier: "en_US"), hints: hints) { text in
            recorder.record(text: text, at: Date().timeIntervalSince(start) * 1000)
        }
        do {
            try await session.start()
        } catch {
            print("stream: start failed: \(error)")
            return 1
        }

        // 100 ms of 16 kHz mono is 1600 samples. Fed at real-time pace so the
        // timings below mean what they say.
        let chunk = 1_600
        var offset = 0
        while offset < pcm.count {
            let end = min(offset + chunk, pcm.count)
            session.append(Array(pcm[offset..<end]))
            offset = end
            try? await Task.sleep(nanoseconds: 100_000_000)
        }
        let audioEndedMs = Date().timeIntervalSince(start) * 1000

        let final: TranscriptionResult
        do {
            final = try await session.finish()
        } catch {
            print("stream: finish failed: \(error)")
            return 1
        }
        let finishedMs = Date().timeIntervalSince(start) * 1000

        let partials = recorder.snapshot()
        print("  audio          \(String(format: "%.2f", duration)) s, fed in \(fmt(audioEndedMs)) ms at real-time pace")
        print("  partials       \(partials.count)")
        for (text, ms) in partials.prefix(12) {
            print("    \(pad(fmt(ms) + " ms", 12)) \"\(display(text))\"")
        }
        if partials.count > 12 { print("    ... \(partials.count - 12) more") }

        let duringSpeech = partials.filter { $0.1 < audioEndedMs }
        print("  first partial  " + (partials.first.map { fmt($0.1) + " ms" } ?? "NONE"))
        print("  during speech  \(duringSpeech.count) of \(partials.count)")
        print("  tail latency   \(fmt(finishedMs - audioEndedMs)) ms  (audio ends -> final text)")
        print("  final          \"\(display(final.best))\"")

        var failures = 0
        if duringSpeech.isEmpty {
            print("  FAIL no partial arrived before the audio ended; this is not streaming")
            failures += 1
        }

        // Same clip, one shot, through the shipped engine.
        let oneShot = TranscriberFactory.make()
        let oneShotText = (try? await oneShot.transcribe(pcm: pcm, hints: hints)) ?? ""
        print("  one-shot       \"\(display(oneShotText))\"")
        if !loosely(final.best, equals: oneShotText) {
            print("  FAIL streaming final differs from the one-shot transcript")
            failures += 1
        }
        if final.best.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
            print("  FAIL streaming produced no final text")
            failures += 1
        }
        return failures
    }

    // MARK: - Onset probe

    /// Measures how much speech the app would lose at the start of an
    /// utterance, which the augmented corpus showed is the single most
    /// expensive degradation there is.
    ///
    /// Two separate delays add up, and they are reported separately because
    /// they have different fixes:
    ///
    ///   start() call duration   how long the keypress handler is blocked
    ///                           bringing up the audio graph.
    ///   onset gap               keypress to the FIRST sample that actually
    ///                           arrives. This is the audio that is gone. It
    ///                           includes the call duration plus however long
    ///                           the hardware takes to deliver its first buffer.
    ///
    /// Needs microphone permission, so run the SIGNED BUNDLE, not the bare
    /// binary: dist/Voicy.app/Contents/MacOS/Voicy --test-onset
    private func runOnsetProbe() async {
        print("")
        print("=== onset probe ===")
        print("How much audio is lost between the keypress and the first captured sample.")

        func measure(prewarmed: Bool, settle: Double) async -> (call: Double, gap: Double?, lost: Double?)? {
            let recorder = MicrophoneRecorder()
            if prewarmed { recorder.prewarm() }
            let t0 = Date()
            do { try recorder.start() } catch {
                print("  mic unavailable: \(error)")
                return nil
            }
            let callMs = Date().timeIntervalSince(t0) * 1000
            // Wait for the hardware to deliver something. Polling rather than
            // sleeping a fixed amount so a fast device is not reported slow.
            let deadline = Date().addingTimeInterval(settle)
            while recorder.onsetGapMs == nil, Date() < deadline {
                await Task.yield()
                try? await Task.sleep(nanoseconds: 1_000_000)
            }
            let gap = recorder.onsetGapMs
            let lost = recorder.capturedGapMs
            _ = recorder.stop()
            return (callMs, gap, lost)
        }

        for (label, prewarmed) in [("cold", false), ("prewarmed", true)] {
            var calls: [Double] = []
            var gaps: [Double] = []
            var losts: [Double] = []
            for _ in 0..<5 {
                guard let result = await measure(prewarmed: prewarmed, settle: 2.0) else { return }
                calls.append(result.call)
                if let gap = result.gap { gaps.append(gap) }
                if let lost = result.lost { losts.append(lost) }
                try? await Task.sleep(nanoseconds: 200_000_000)
            }
            let gapText = gaps.isEmpty ? "never" : fmt(Percentile.of(gaps, 0.5)) + " ms"
            let lostText = losts.isEmpty ? "unavailable" : fmt(Percentile.of(losts, 0.5)) + " ms"
            print("  \(pad(label, 12)) start() \(pad(fmt(Percentile.of(calls, 0.5)) + " ms", 10)) "
                  + "first callback \(pad(gapText, 10)) AUDIO LOST \(lostText)")
            if gaps.count < calls.count {
                print("    \(calls.count - gaps.count)/\(calls.count) attempts delivered NO audio within 2 s")
            }
        }

        print("")
        print("\"first callback\" is when the tap fired; most of it is the 4096-frame tap")
        print("buffer filling up, and that audio is INSIDE the buffer, not missing.")
        print("\"AUDIO LOST\" compares start() against the hardware timestamp of the first")
        print("captured sample, so it is the audio that genuinely never existed anywhere.")
        print("That is the only part a pre-roll buffer could recover.")
    }

    // MARK: - WER / CER evaluation

    /// Scores the recognizer itself, separately from the intent pipeline.
    ///
    /// The suite mode above answers "did the pipeline produce the right
    /// recipient and body". This mode answers the different and more honest
    /// question "how many words did the recognizer get wrong", which is the
    /// number that moves when transcription quality actually changes. A clip can
    /// pass the suite while mangling a name, so the suite alone cannot tell
    /// improvement from regression.
    ///
    ///   --test-wer <manifest>      score every clip in the manifest
    ///   --wer-out <file.tsv>       write per-clip scores, for later comparison
    ///   --wer-compare <file.tsv>   print this run against an earlier --wer-out
    private func runWER(manifestPath: String) async -> Int {
        let manifestURL = URL(fileURLWithPath: manifestPath)
        guard let text = try? String(contentsOf: manifestURL, encoding: .utf8) else {
            print("wer: could not read manifest at \(manifestPath)")
            return 1
        }
        let dir = manifestURL.deletingLastPathComponent()
        let cases = AudioManifest.parse(text)
        guard !cases.isEmpty else {
            print("wer: manifest has no cases")
            return 1
        }

        let contacts = await contactSet()
        let engine = await warmEngine()
        let hints = has("--no-hints") ? [] : contacts.flatMap { c in
            [c.givenName, c.familyName, c.nickname, c.organizationName, c.displayName]
                .filter { !$0.isEmpty }
        }

        struct Row {
            let name: String
            let reference: String
            let hypothesis: String
            let wer: ErrorRate.Score
            let cer: ErrorRate.Score
            let ms: Double
            let failed: String?
        }

        var rows: [Row] = []
        var missing = 0

        for testCase in cases {
            let audioURL = dir.appendingPathComponent("\(testCase.name).wav")
            guard let pcm = try? AudioFileLoader.loadPCM(url: audioURL), !pcm.isEmpty else {
                print("MISSING \(testCase.name): no audio at \(audioURL.path)")
                missing += 1
                continue
            }
            let start = Date()
            var hypothesis = ""
            var failure: String?
            do {
                hypothesis = try await engine.transcribe(pcm: pcm, hints: hints)
            } catch {
                failure = "transcribe: \(error)"
            }
            let ms = Date().timeIntervalSince(start) * 1000
            if failure == nil, hypothesis.trimmingCharacters(in: .whitespacesAndNewlines).isEmpty {
                failure = "empty transcript from \(String(format: "%.1f", AudioFileLoader.duration(pcm))) s of audio"
            }
            rows.append(Row(
                name: testCase.name,
                reference: testCase.spoken,
                hypothesis: hypothesis,
                wer: ErrorRate.word(reference: testCase.spoken, hypothesis: hypothesis),
                cer: ErrorRate.character(reference: testCase.spoken, hypothesis: hypothesis),
                ms: ms,
                failed: failure
            ))
        }

        guard !rows.isEmpty else {
            print("wer: no clips scored (\(missing) missing)")
            return 1
        }

        print("")
        print("=== WER / CER over \(rows.count) clip(s) ===")
        print("\(pad("clip", 30)) \(pad("WER", 8)) \(pad("CER", 8)) \(pad("S/D/I", 10)) \(pad("ms", 8)) transcript")
        for row in rows.sorted(by: { $0.wer.rate > $1.wer.rate }) {
            let sdi = "\(row.wer.substitutions)/\(row.wer.deletions)/\(row.wer.insertions)"
            print("\(pad(row.name, 30)) \(pad(pct(row.wer.rate), 8)) \(pad(pct(row.cer.rate), 8)) "
                  + "\(pad(sdi, 10)) \(pad(fmt(row.ms), 8)) \"\(display(row.hypothesis))\"")
            if let failed = row.failed { print("       ERROR \(failed)") }
        }

        let corpusWER = ErrorRate.corpus(rows.map(\.wer))
        let corpusCER = ErrorRate.corpus(rows.map(\.cer))
        let times = rows.map(\.ms)
        print("")
        print("corpus WER \(pct(corpusWER.rate))  (\(corpusWER.substitutions) sub, "
              + "\(corpusWER.deletions) del, \(corpusWER.insertions) ins over \(corpusWER.referenceLength) words)")
        print("corpus CER \(pct(corpusCER.rate))")
        print("clean clips (WER 0): \(rows.filter { $0.wer.errors == 0 }.count)/\(rows.count)")
        print("latency: median \(fmt(Percentile.of(times, 0.5))) ms  p95 \(fmt(Percentile.of(times, 0.95))) ms  "
              + "max \(fmt(times.max() ?? 0)) ms")
        if missing > 0 { print("missing audio for \(missing) clip(s)") }

        // Per-variant rollup. Augmented clips are named "<base>.<variant>", so
        // this shows which degradation (noise, gain, rate) actually costs
        // accuracy instead of hiding it inside one corpus average.
        let grouped = Dictionary(grouping: rows) { row -> String in
            let parts = row.name.split(separator: ".")
            return parts.count > 1 ? String(parts.last!) : "clean"
        }
        if grouped.count > 1 {
            print("")
            print("by variant:")
            for key in grouped.keys.sorted() {
                let group = grouped[key]!
                let score = ErrorRate.corpus(group.map(\.wer))
                let groupTimes = group.map(\.ms)
                print("  \(pad(key, 18)) n=\(pad(String(group.count), 4)) WER \(pad(pct(score.rate), 8)) "
                      + "CER \(pad(pct(ErrorRate.corpus(group.map(\.cer)).rate), 8)) "
                      + "median \(fmt(Percentile.of(groupTimes, 0.5))) ms")
            }
        }

        if let outPath = value(for: "--wer-out") {
            let tsv = rows.map { row in
                [row.name, String(format: "%.4f", row.wer.rate), String(format: "%.4f", row.cer.rate),
                 String(format: "%.1f", row.ms), row.hypothesis].joined(separator: "\t")
            }.joined(separator: "\n") + "\n"
            do {
                try tsv.write(to: URL(fileURLWithPath: outPath), atomically: true, encoding: .utf8)
                print("wrote \(outPath)")
            } catch {
                print("could not write \(outPath): \(error)")
            }
        }

        if let comparePath = value(for: "--wer-compare") {
            compareWER(rows.map { ($0.name, $0.wer.rate, $0.hypothesis) }, against: comparePath)
        }

        // Every clip must produce SOME transcript. A hard failure (throw or
        // empty output) is a bug regardless of the error rate, so it is the
        // only thing this mode fails on. Error rates are reported, never
        // silently thresholded: a threshold here would just get loosened.
        let hardFailures = rows.filter { $0.failed != nil }.count + missing
        return hardFailures
    }

    private func compareWER(_ current: [(String, Double, String)], against path: String) {
        guard let text = try? String(contentsOfFile: path, encoding: .utf8) else {
            print("compare: could not read \(path)")
            return
        }
        var baseline: [String: (Double, String)] = [:]
        for line in text.split(separator: "\n") {
            let f = line.split(separator: "\t", omittingEmptySubsequences: false).map(String.init)
            guard f.count >= 5, let rate = Double(f[1]) else { continue }
            baseline[f[0]] = (rate, f[4])
        }
        print("")
        print("=== change vs \(path) ===")
        var better = 0, worse = 0, same = 0
        for (name, rate, hypothesis) in current {
            guard let (was, wasText) = baseline[name] else {
                print("  NEW    \(pad(name, 30)) WER \(pct(rate))")
                continue
            }
            let delta = rate - was
            if abs(delta) < 0.0001 { same += 1; continue }
            if delta < 0 { better += 1 } else { worse += 1 }
            print("  \(delta < 0 ? "BETTER" : "WORSE ") \(pad(name, 30)) "
                  + "WER \(pct(was)) -> \(pct(rate))")
            print("         was \"\(display(wasText))\"")
            print("         now \"\(display(hypothesis))\"")
        }
        print("  \(better) better, \(worse) worse, \(same) unchanged")
    }

    private func pct(_ rate: Double) -> String { String(format: "%.1f%%", rate * 100) }

    // MARK: - Unit tests (no audio, no permissions)

    private func runUnitTests() async -> Int {
        print("=== unit tests ===")
        var failed = 0

        let intent = runIntentTests()
        print("intent parser: \(intent.passed) passed, \(intent.failed) failed")
        failed += intent.failed

        let contacts = runContactTests()
        print("contacts:      \(contacts.passed) passed, \(contacts.failed) failed")
        failed += contacts.failed

        let send = runSendTests()
        print("send:          \(send.passed) passed, \(send.failed) failed")
        failed += send.failed

        let cleanup = runCleanupTests()
        print("cleanup:       \(cleanup.passed) passed, \(cleanup.failed) failed")
        failed += cleanup.failed

        let sendGuard = await runSendGuardTests()
        print("send guard:    \(sendGuard.passed) passed, \(sendGuard.failed) failed")
        failed += sendGuard.failed

        let sendPath = await runSendPathTests()
        print("send path:     \(sendPath.passed) passed, \(sendPath.failed) failed")
        failed += sendPath.failed

        return failed
    }

    // MARK: - Latency probe

    private func runLatencyProbe() async {
        print("")
        print("=== latency probe ===")

        // Cold engine construction + first transcription, the number the user
        // actually feels on the first utterance after launch.
        let coldStart = Date()
        let cold = TranscriberFactory.make()
        let constructMs = Date().timeIntervalSince(coldStart) * 1000
        let silence = [Float](repeating: 0, count: 16_000)
        let firstStart = Date()
        _ = try? await cold.transcribe(pcm: silence, hints: [])
        let firstMs = Date().timeIntervalSince(firstStart) * 1000
        let secondStart = Date()
        _ = try? await cold.transcribe(pcm: silence, hints: [])
        let secondMs = Date().timeIntervalSince(secondStart) * 1000

        print("  construct engine        \(fmt(constructMs)) ms")
        print("  first  transcribe (1 s) \(fmt(firstMs)) ms  <- paid once, at launch, if warmed")
        print("  second transcribe (1 s) \(fmt(secondMs)) ms  <- what the user feels")
        print("  warm-up saves           \(fmt(max(0, firstMs - secondMs))) ms on the first utterance")

        // Microphone engine start, the 100 ms budget item. Measured twice: cold,
        // and after `prewarm()` has run the way the shipped app does at launch.
        // Needs mic permission; reports honestly when it is unavailable.
        do {
            let cold = MicrophoneRecorder()
            let coldMicStart = Date()
            try cold.start()
            let coldMs = Date().timeIntervalSince(coldMicStart) * 1000
            _ = cold.stop()

            let warm = MicrophoneRecorder()
            warm.prewarm()
            let warmMicStart = Date()
            try warm.start()
            let warmMs = Date().timeIntervalSince(warmMicStart) * 1000
            _ = warm.stop()

            print("  mic start, cold         \(fmt(coldMs)) ms  (budget 100 ms)"
                  + (coldMs > 100 ? "  OVER BUDGET" : ""))
            print("  mic start, prewarmed    \(fmt(warmMs)) ms  (budget 100 ms)"
                  + (warmMs > 100 ? "  OVER BUDGET" : ""))
            print("  prewarm saves           \(fmt(max(0, coldMs - warmMs))) ms at key-down")
        } catch {
            print("  mic engine start        unavailable: \(error)")
        }
    }

    // MARK: - Formatting

    private func fmt(_ ms: Double) -> String { String(format: "%.1f", ms) }

    private func pad(_ s: String, _ width: Int) -> String {
        s.count >= width ? s : s + String(repeating: " ", count: width - s.count)
    }
}

// MARK: - Manifest

/// Parser for the tab-separated audio manifest shared by the generator script
/// and the suite runner.
enum AudioManifest {
    struct Case {
        let name: String
        let voice: String
        let spoken: String
        let expectRecipient: String
        let expectBody: String
        let expectResolution: String
    }

    static func parse(_ text: String) -> [Case] {
        text.split(separator: "\n", omittingEmptySubsequences: false).compactMap { rawLine in
            let line = String(rawLine)
            guard !line.trimmingCharacters(in: .whitespaces).isEmpty,
                  !line.hasPrefix("#") else { return nil }
            let f = line.split(separator: "\t", omittingEmptySubsequences: false).map(String.init)
            guard f.count >= 3 else { return nil }
            return Case(name: f[0].trimmingCharacters(in: .whitespaces),
                        voice: f[1].trimmingCharacters(in: .whitespaces),
                        spoken: f[2],
                        expectRecipient: f.count > 3 ? f[3] : "",
                        expectBody: f.count > 4 ? f[4] : "",
                        expectResolution: f.count > 5 ? f[5].trimmingCharacters(in: .whitespaces) : "")
        }
    }
}
